language: python
python:
  - "3.5"


# command to install dependencies
install:
    - pip install tox


# command to run tests

script:
    - tox


after_success:
  - bash <(curl -s https://codecov.io/bash) -t 6c24803c-ddea-4fc1-990e-3ff2d759093b
